FROM nginx
WORKDIR /usr/share/nginx/html
COPY helloworld.html .
# The Dockerfile EXPOSE statement is for metadata purposes only. It has no effect on actual port mapping, it just tells the user of an image to expect a service to listen on the port(s).
EXPOSE 80